'use strict';
// Options observed in the Sanjit account on 5 September 2026.
const sourceBreakdowns={Time:['Day','Week','2 weeks','Month'],Demographics:['Age','Gender','Age and gender','Audience segments'],Geography:['Country','Country and audience segments','Region','Business locations'],Delivery:['Placement','Platform','Reels trending topic','Time of day (ad account time zone)','Media type','Product ID'],Action:['Messaging purchase source','Messaging outcome destination','Prompts and responses','Conversion device','Carousel card','Destination','Post reaction type','Brand','Category','Video sound','Video view type'],Creative:['Flexible format','Related media'],Attribution:['Attribution settings','Conversion count']};
const additionalBreakdowns={Geography:['Comscore Markets'],Delivery:["Time of day (viewer's time zone)",'Impression device','Platform and device','Placement and device']};
let breakdownSelection={},breakdownAnchor=null,breakdownCategory='',breakdownQuery='';
function breakdownChoice(name,group,radio=false){const checked=breakdownSelection[group]===name;return `<button class="breakdown-choice" role="${radio?'menuitemradio':'menuitemcheckbox'}" aria-checked="${checked}" data-action="bd-select:${esc(group)}|${esc(name)}"><span class="breakdown-control ${radio?'radio':''} ${checked?'checked':''}">${checked&&!radio?'✓':''}</span><span>${esc(name)}${name==='Time of day (ad account time zone)'?'<small>Available for the last 13 months.</small>':''}</span></button>`}
function breakdownGroup(name){return Object.keys(sourceBreakdowns).find(g=>sourceBreakdowns[g].includes(name))}
function breakdownMainContent(){const q=breakdownQuery.toLowerCase();if(q)return [...Object.entries(sourceBreakdowns)].map(([group,values])=>{const matches=values.filter(v=>v.toLowerCase().includes(q));return matches.length?heading(group)+matches.map(v=>breakdownChoice(v,group)).join(''):''}).join('')||'<p class="muted">No breakdowns found</p>';return `${btn('View breakdown charts','bd-charts','chart','','disabled')}<hr class="menu-separator">${heading('Recently used')}${['Placement','Region','Age'].map(n=>breakdownChoice(n,breakdownGroup(n))).join('')}<hr class="menu-separator">${heading('Popular')}${['Day','Age','Placement','Country','Platform'].map(n=>breakdownChoice(n,breakdownGroup(n))).join('')}<hr class="menu-separator">${Object.keys(sourceBreakdowns).map(g=>`<button class="breakdown-category" data-action="bd-category:${g}" aria-haspopup="menu" aria-expanded="${breakdownCategory===g}">${g}<span>›</span></button>`).join('')}<hr class="menu-separator"><button class="breakdown-choice" disabled><span class="breakdown-control"></span><span>Value rules<small>Ads and ad sets only</small></span></button>${Object.keys(breakdownSelection).length?btn('Clear all breakdowns','bd-clear','','text-link'):''}`}
showBreakdowns=function(anchor){breakdownAnchor=anchor||breakdownAnchor;breakdownCategory='';breakdownQuery='';menu(breakdownAnchor,`<div class="breakdown-shell"><input id="breakdown-search" type="search" placeholder="Search" aria-label="Search breakdowns"><div id="breakdown-main" role="menu">${breakdownMainContent()}</div></div><div id="breakdown-flyout" role="menu" hidden></div>`,244);$('#popover').classList.add('breakdown-popover');$('#breakdown-search').addEventListener('input',e=>{breakdownQuery=e.target.value;$('#breakdown-main').innerHTML=breakdownMainContent();$('#breakdown-flyout').hidden=true})};
function openBreakdownCategory(group,el){if(!sourceBreakdowns[group])return;breakdownCategory=group;$('#popover').hidden=false;const fly=$('#breakdown-flyout');fly.innerHTML=`<button class="breakdown-choice" role="menuitemradio" aria-checked="${!breakdownSelection[group]}" data-action="bd-select:${group}|" ${!breakdownSelection[group]?'disabled':''}><span class="breakdown-control radio ${!breakdownSelection[group]?'checked':''}"></span>None</button>${sourceBreakdowns[group].map(n=>breakdownChoice(n,group,true)).join('')}${additionalBreakdowns[group]?heading('Additional breakdowns')+additionalBreakdowns[group].map(n=>`<button class="breakdown-choice" disabled><span class="breakdown-control radio"></span><span>${esc(n)}<small class="enable-breakdown">Enable breakdown</small></span></button>`).join(''):''}`;fly.hidden=false;const rect=el.getBoundingClientRect();fly.style.width='285px';fly.style.left=(rect.right+285<innerWidth?rect.right:Math.max(8,rect.left-285))+'px';fly.style.top=Math.max(8,Math.min(rect.top,innerHeight-fly.offsetHeight-8))+'px'}
const actionBeforeBreakdowns=action;
action=function(value,el){if(value.startsWith('bd-category:')){openBreakdownCategory(value.slice(12),el);return}if(value.startsWith('bd-select:')){const [group,name]=value.slice(10).split('|');if(!sourceBreakdowns[group]||name&&!sourceBreakdowns[group].includes(name))return;if(!name||breakdownSelection[group]===name)delete breakdownSelection[group];else breakdownSelection[group]=name;state.breakdown=Object.values(breakdownSelection).join(', ');render();return}if(value==='bd-clear'){breakdownSelection={};state.breakdown='';render();return}return actionBeforeBreakdowns(value,el)};
const menuBeforeBreakdowns=menu;
menu=function(...args){$('#popover').classList.remove('breakdown-popover');return menuBeforeBreakdowns(...args)};
document.addEventListener('keydown',e=>{const target=e.target.closest('[data-action^="bd-category:"]');if(target&&e.key==='ArrowRight'){e.preventDefault();openBreakdownCategory(target.dataset.action.slice(12),target)}if(e.key==='Escape'&&$('#breakdown-flyout')&&!$('#breakdown-flyout').hidden){$('#breakdown-flyout').hidden=true}});
document.addEventListener('mouseover',e=>{const target=e.target.closest('[data-action^="bd-category:"]');if(target)openBreakdownCategory(target.dataset.action.slice(12),target)});
