'use strict';
const columnGroups={
'Key metrics':{
'Results':['Cost per result','Results ROAS','Result rate','Results value','Results'],
'Spend':['Amount spent','Amount spent percentage'],
'Impressions':['Cost per 1,000 Meta accounts reached','Impressions','CPM (cost per 1,000 impressions)','Reach','Frequency'],
'Views':['Viewers','Views'],
'Media':['2-second continuous video plays','Cost per ThruPlay','3-second video plays','ThruPlays','Cost per 2-second continuous video play','Unique 2-second continuous video plays','Cost per 3-second video play','Video plays'],
'Clicks':['Clicks (all)','Photo clicks','Cost per unique click (all)','Shop clicks','CPC (all)','Unique clicks (all)','CPC (cost per link click)','Unique CTR (all)','CTR (all)','Unique CTR (link click-through rate)','CTR (link click-through rate)','Unique link clicks','Link clicks'],
'Traffic':['Cost per landing page view','Website landing page views','Instagram profile visits'],
'Follows & likes':['Cost per like','Instagram follows','Facebook likes'],
'Engagement':['Check-ins','Net reminders on','Cost per event response','Page engagement','Cost per join group request','Post comments','Cost per Page engagement','Post engagements','Cost per post engagement','Post reactions','Event responses','Post saves','Join group requests','Post shares'],
'Messaging':['Cost per message delivered','Messages delivered','Cost per messaging conversation started','Messaging conversations replied','Cost per messaging subscription','Messaging conversations started','Cost per returning messaging contact','Messaging subscriptions','Marketing messages CTR','Returning messaging contacts','Marketing messages read','Welcome message views'],
'Standard events':['Adds to cart','Checkouts initiated','Content views','Donation ROAS (return on ad spend)','Leads','Website leads','Offline leads','Meta leads','Purchase ROAS (return on ad spend)','Purchases','In-app purchases','Website purchases','Offline purchases','Meta purchases'],
'Custom conversions':['meeting','Meeting Booked']},
'Tracking':{'Ad relevance':['Conversion rate ranking','Quality ranking','Engagement rate ranking'],'Messaging and calling':['Blocks'],'Media':['Video plays at 25%','Video plays at 95%','Video plays at 50%','Video plays at 100%','Video plays at 75%']},
'Ad settings':{'Status and dates':['Actions','Ends','Ad set delivery','Last significant edit','Attribution setting','Reporting ends','Date created','Reporting starts','Date last edited','Starts','Delivery','Time elapsed percentage'],'Goal, budget & schedule':['Ad schedule','Campaign spending limit','Bid strategy','Conversion location','Budget','Objective','Budget remaining','Performance goal','Buying type','Schedule'],'Object names and IDs':['Account ID','Ad set name','Account name','Campaign ID','Ad ID','Campaign name','Ad name','Tags','Ad set ID'],'Targeting':['Audience age (ad set settings)','Excluded custom audiences','Audience gender (ad set settings)','Included custom audiences','Audience location (ad set settings)'],'Ad creative':['Body (ad settings)','Link (ad settings)','Destination','Page name','Headline (ad settings)','Preview link'],'Tracking source':['App event','URL parameters','Offline event','Web event']},
'Advanced':{'Impressions':['Gross impressions (includes invalid impressions from non-human traffic)'],'Brand lift':['Cost per ad recall lift','Estimated ad recall lift rate','Estimated ad recall lift (people)'],'Performance funnel':['Landing page views rate per link clicks','Results rate per link clicks']},
'Custom':{'Only you':['14dayconversion','Link to LP','Conversion','link to lp ratio','conversion rate'],'Everyone with access to this business':['Hold Rate','Hook Rate']}};
if(Object.keys(company.metricFormats||{}).length)columnGroups.Custom['Company metrics']=Object.keys(company.metricFormats).map(key=>columns.find(c=>c[0]===key)?.[1]||key);
const metricKey=name=>columns.find(c=>c[1]===name)?.[0]||name;
for(const groups of Object.values(columnGroups))for(const names of Object.values(groups))for(const name of names)if(!columns.some(c=>c[1]===name))columns.push([name,name,/ID$|settings\)/.test(name)?190:150]);
const conversionFamilies={'Leads':['Website leads','Offline leads','Meta leads'],'Purchases':['In-app purchases','Website purchases','Offline purchases','Meta purchases']};
const conversionRows={'Standard events':[['Adds to cart','Adds to cart','Adds to cart conversion value','Cost per add to cart'],['Checkouts initiated','Checkouts initiated','Checkouts initiated conversion value','Cost per checkout initiated'],['Content views','Content views','Content views conversion value','Cost per content view'],['Donation ROAS (return on ad spend)','Donation ROAS (return on ad spend)',null,null],['Landing page views','Website landing page views',null,'Cost per landing page view'],['Leads','Leads','Leads conversion value','Cost per lead'],['Purchase ROAS (return on ad spend)','Purchase ROAS (return on ad spend)',null,null],['Purchases','Purchases','Purchases conversion value','Cost per purchase']],'Custom conversions':[['meeting','meeting','meeting conversion value','Cost per meeting'],['Meeting Booked','Meeting Booked','Meeting Booked conversion value','Cost per Meeting Booked']]};
for(const rows of Object.values(conversionRows))for(const row of rows)for(const name of row.slice(1))if(name&&!columns.some(c=>c[0]===metricKey(name)))columns.push([name,name,160]);
function conversionGrid(group,query=''){const rows=conversionRows[group].filter(row=>!query||row.some(n=>n&&n.toLowerCase().includes(query)));if(!rows.length)return '';return `<div class="conversion-grid"><b>Conversions</b><span>Total</span><span>Value</span><span>Cost</span>${rows.map(([label,...names])=>`<span class="conversion-label">${esc(label)}</span>${names.map((name,i)=>`<label><input type="checkbox" name="source-column" aria-label="${esc(label)} ${['Total','Value','Cost'][i]}" value="${esc(name?metricKey(name):'')}" ${!name?'disabled':columnDraft.includes(metricKey(name))?'checked':''}></label>`).join('')}`).join('')}</div>`}
let editorTab='Key metrics',editorQuery='',editorCollapsed=false,columnDragIndex=null,columnPresetName='';
function metricCheck(name){const key=metricKey(name);return `<label class="metric-choice"><input type="checkbox" name="source-column" value="${esc(key)}" ${columnDraft.includes(key)?'checked':''}><span>${esc(name)}</span></label>`}
function metricCatalogHTML(){const query=editorQuery.toLowerCase();const tabs=query?Object.keys(columnGroups):[editorTab];let html='';if(!query&&editorTab==='Key metrics')html=`<section class="column-suggestions"><b>Suggested columns ⓘ</b><div class="metric-grid">${['CPM (cost per 1,000 impressions)','Purchase ROAS (return on ad spend)','Frequency','Purchases'].map(metricCheck).join('')}</div></section>`;for(const tab of tabs)for(const [group,names] of Object.entries(columnGroups[tab])){const searchable=conversionRows[group]?conversionRows[group].flat().filter(Boolean):names;const matches=searchable.filter(n=>!query||n.toLowerCase().includes(query));if(matches.length){const count=names.filter(n=>columnDraft.includes(metricKey(n))).length;html+=`<details class="metric-group" ${!editorCollapsed||query?'open':''}><summary>${esc(group)}${count?`<small>${count} selected</small>`:''}</summary>${conversionRows[group]?conversionGrid(group,query):`<div class="metric-grid">${matches.map(metricCheck).join('')}</div>`}</details>`}}return html||'<p class="muted">No matching metrics or column settings</p>'}
function drawColumnSelection(){const panel=$('#column-selection');const children=new Set(Object.entries(conversionFamilies).filter(([p])=>columnDraft.includes(p)).flatMap(([,c])=>c));panel.innerHTML=`<h3>${columnDraft.length+1} columns selected</h3><p>Drag and drop to reorder.</p><div class="column-selection-list"><div class="column-selected fixed">${singular[state.level]}</div>${columnDraft.map((key,i)=>children.has(key)?'':`<div class="column-selected-group"><div class="column-selected" draggable="true" data-column-index="${i}"><span class="column-drag">⠿</span><span>${esc(columns.find(c=>c[0]===key)?.[1]||key)}</span><div class="column-reorder">${btn('↑',`ce-up:${i}`,'','','aria-label="Move '+esc(key)+' up"')}${btn('↓',`ce-down:${i}`,'','','aria-label="Move '+esc(key)+' down"')}</div>${btn('×',`ce-remove:${i}`,'','','aria-label="Remove '+esc(key)+'"')}</div>${conversionFamilies[key]?`<div class="column-subcategories">${conversionFamilies[key].map(name=>`<label><input type="checkbox" name="source-subcategory" value="${esc(name)}" data-parent="${esc(key)}" ${columnDraft.includes(name)?'checked':''}>${esc(name)}</label>`).join('')}</div>`:''}</div>`).join('')}</div>`}
function drawMetricCatalog(){$('#metric-catalog').innerHTML=metricCatalogHTML();drawColumnSelection()}
customiseColumns=function(){columnDraft=[...state.visible];editorTab='Key metrics';editorQuery='';editorCollapsed=false;columnPresetName=state.preset;const d=$('#modal');d.style.width='976px';d.classList.remove('source-preview-modal','pm-advanced');d.classList.add('source-column-modal');d.innerHTML=`<div class="modal-head"><h2 id="column-preset-title">${esc(columnPresetName)}</h2>${btn('✎','ce-rename','','text-link','aria-label="Edit preset name"')}${ib('Close','close-modal','close')}</div><div class="source-column-layout"><section class="column-catalog-area"><div class="column-search-row"><input id="column-search" type="search" aria-label="Search metrics" placeholder="Search for metrics or column settings">${btn('Collapse all','ce-collapse')}</div><div class="column-tabs" role="tablist">${Object.keys(columnGroups).map(tab=>`<button role="tab" aria-selected="${tab===editorTab}" data-action="ce-tab:${tab}">${tab}</button>`).join('')}</div><div id="metric-catalog"></div></section><aside id="column-selection"></aside></div><div class="modal-footer">${btn('Compare attribution settings','attribution')}${btn('Cancel','close-modal')}${btn('Save','ce-save','','primary')}</div>`;$('#popover').hidden=true;d.showModal();drawMetricCatalog();$('#column-search').addEventListener('input',e=>{editorQuery=e.target.value;drawMetricCatalog()})};
function moveColumn(from,to){if(from<0||from>=columnDraft.length||to<0||to>=columnDraft.length||from===to)return;const children=new Set(Object.entries(conversionFamilies).filter(([p])=>columnDraft.includes(p)).flatMap(([,c])=>c));const roots=columnDraft.filter(k=>!children.has(k));const owner=k=>Object.entries(conversionFamilies).find(([p,c])=>columnDraft.includes(p)&&c.includes(k))?.[0]||k;const key=owner(columnDraft[from]);let target=owner(columnDraft[to]);let a=roots.indexOf(key),b=roots.indexOf(target);if(a===b)b=Math.max(0,Math.min(roots.length-1,a+(to>from?1:-1)));roots.splice(a,1);roots.splice(b,0,key);const previous=[...columnDraft];columnDraft=roots.flatMap(k=>[k,...(conversionFamilies[k]||[]).filter(c=>previous.includes(c))]);drawColumnSelection()}
const actionBeforeColumnEditor=action;
action=function(value,el){if(value.startsWith('ce-tab:')){editorTab=value.slice(7);$$('.column-tabs button').forEach(b=>b.setAttribute('aria-selected',String(b.textContent===editorTab)));drawMetricCatalog();return}if(value==='ce-collapse'){editorCollapsed=!editorCollapsed;el.textContent=editorCollapsed?'Expand all':'Collapse all';drawMetricCatalog();return}if(value.startsWith('ce-remove:')){const key=columnDraft[Number(value.slice(10))];columnDraft=columnDraft.filter(k=>k!==key&&!(conversionFamilies[key]||[]).includes(k));drawMetricCatalog();return}if(value.startsWith('ce-up:')){const i=Number(value.slice(6));moveColumn(i,i-1);return}if(value.startsWith('ce-down:')){const i=Number(value.slice(8));moveColumn(i,i+1);return}if(value==='ce-rename'){$('#column-preset-title').innerHTML=`<input id="column-preset-name" aria-label="Preset name" value="${esc(columnPresetName)}">`;$('#column-preset-name').focus();return}if(value==='ce-save'){if(!columnDraft.length)return toast('Select at least one metric.');state.visible=[...columnDraft];state.preset=columnPresetName.trim()||'Custom';persist();$('#modal').close();render();return}return actionBeforeColumnEditor(value,el)};
const modalBeforeColumnEditor=modal;
modal=function(...args){$('#modal').classList.remove('source-column-modal');return modalBeforeColumnEditor(...args)};
document.addEventListener('change',e=>{if(e.target.name==='source-column'){const key=e.target.value;if(e.target.checked&&!columnDraft.includes(key))columnDraft.push(key);else if(!e.target.checked)columnDraft=columnDraft.filter(k=>k!==key);drawMetricCatalog()}if(e.target.id==='column-preset-name')columnPresetName=e.target.value});
document.addEventListener('dragstart',e=>{const row=e.target.closest('[data-column-index]');if(row){columnDragIndex=Number(row.dataset.columnIndex);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(columnDragIndex))}});
document.addEventListener('dragover',e=>{if(e.target.closest('[data-column-index]'))e.preventDefault()});
document.addEventListener('drop',e=>{const row=e.target.closest('[data-column-index]');if(row&&columnDragIndex!==null){e.preventDefault();moveColumn(columnDragIndex,Number(row.dataset.columnIndex));columnDragIndex=null}});
const formatBeforeColumns=format;
format=function(r,key){if(/ ID$| name$|ad settings|^Preview link$|^URL parameters$/.test(key))return esc(r[key]||'—');return formatBeforeColumns(r,key)};

document.addEventListener('change',e=>{if(e.target.name!=='source-subcategory')return;setConversionSubcategory(e.target.dataset.parent,e.target.value,e.target.checked)});
function setConversionSubcategory(parent,key,checked){if(!(conversionFamilies[parent]||[]).includes(key)||!columnDraft.includes(parent))return;columnDraft=columnDraft.filter(k=>k!==key);if(checked){const siblings=conversionFamilies[parent].filter(k=>k===key||columnDraft.includes(k));columnDraft=columnDraft.filter(k=>!conversionFamilies[parent].includes(k));columnDraft.splice(columnDraft.indexOf(parent)+1,0,...siblings)}drawMetricCatalog()}
