'use strict';
const formattingColours={Red:'#f7c8cb',Yellow:'#fff0b3',Green:'#c9ebd3',Blue:'#cde6fa',Purple:'#e1ceef',Pink:'#f5cee4',white:'#ffffff'};
for(const [name,hex] of Object.entries(formattingColours))formattingColours[name.toLowerCase()]=hex;
const formattingOperators=['Greater than','Greater than or equal to','In range','Less than','Less than or equal to','Not in range'];
const formattingPalettes=['Green, white','Red, white','Yellow, white','Green, white, red','Green, yellow, red','Purple, white','Pink, white','Pink, white, purple'];
let formattingRules=[];try{formattingRules=JSON.parse(localStorage.getItem(STORAGE+':formatting')||JSON.stringify(company.formattingRules||[]));if(!Array.isArray(formattingRules))formattingRules=[]}catch{}
formattingRules=formattingRules.filter(r=>r&&typeof r==='object').map(r=>({event:'All events',...r,id:r.id||crypto.randomUUID()}));
let formattingDraft=null,formattingRows=[];
function finiteMetric(value){return value!==null&&value!==undefined&&String(value).trim()!==''&&Number.isFinite(Number(value))?Number(value):null}
function formattingMatches(value,rule){const n=finiteMetric(value);if(n===null)return false;const a=Number(rule.value),b=Number(rule.upper);return {'Greater than':n>a,'Greater than or equal to':n>=a,'Less than':n<a,'Less than or equal to':n<=a,'In range':n>=a&&n<=b,'Not in range':n<a||n>b}[rule.operator]||false}
function scaleBoundary(type,value,min,max){return type==='Min. value'?min:type==='Max. value'?max:type==='Percentage'?min+(max-min)*Number(value)/100:Number(value)}
function blendColour(a,b,t){t=Math.max(0,Math.min(1,t));const rgb=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));const x=rgb(a),y=rgb(b);return '#'+x.map((v,i)=>Math.round(v+(y[i]-v)*t).toString(16).padStart(2,'0')).join('')}
function ruleColour(row,rule,rows){if(rule.enabled===false||rule.level!==state.level||!validFormattingRule(rule)||rule.event!=='All events'&&resultType(row)!==rule.event)return '';const n=finiteMetric(row[rule.key]);if(n===null)return '';if(rule.mode==='Single colour')return formattingMatches(n,rule)?formattingColours[rule.colour]:'';const values=rows.filter(r=>rule.event==='All events'||resultType(r)===rule.event).map(r=>finiteMetric(r[rule.key])).filter(v=>v!==null);if(!values.length)return '';const min=Math.min(...values),max=Math.max(...values);const low=scaleBoundary(rule.minType,rule.min,min,max),high=scaleBoundary(rule.maxType,rule.max,min,max);if(high<low)return '';let colours=rule.palette.split(', ').map(c=>formattingColours[c]);if(rule.flip)colours.reverse();if(high===low)return colours[Math.floor(colours.length/2)];if(colours.length===2)return blendColour(colours[0],colours[1],(n-low)/(high-low));const middle=scaleBoundary(rule.midType,rule.mid,min,max);if(middle<=low||middle>=high)return '';return n<=middle?blendColour(colours[0],colours[1],(n-low)/(middle-low)):blendColour(colours[1],colours[2],(n-middle)/(high-middle))}
function validFormattingRule(r){if(!r||!columns.some(c=>c[0]===r.key)||!['campaigns','adsets','ads'].includes(r.level))return false;if(r.mode==='Single colour')return formattingOperators.includes(r.operator)&&['Red','Yellow','Green','Blue'].includes(r.colour)&&finiteMetric(r.value)!==null&&(!r.operator.includes('range')||finiteMetric(r.upper)!==null&&Number(r.upper)>=Number(r.value));if(r.mode!=='Colour scale'||!formattingPalettes.includes(r.palette))return false;if(r.minType==='Numeric'&&r.maxType==='Numeric'&&Number(r.min)>Number(r.max))return false;return [['minType','min','Min. value'],['midType','mid','Percentage'],['maxType','max','Max. value']].every(([type,key,auto])=>{if(key==='mid'&&r.palette.split(', ').length===2)return true;if(![auto,'Numeric','Percentage'].includes(r[type]))return false;if(r[type]==='Min. value'||r[type]==='Max. value')return true;const v=finiteMetric(r[key]);return v!==null&&(r[type]!=='Percentage'||v>=0&&v<=100)})}
function saveFormattingRules(){try{localStorage.setItem(STORAGE+':formatting',JSON.stringify(formattingRules))}catch{toast('Could not save formatting in this browser.')}renderTable()}
cellFormatting=function(row,key){let colour='';for(const rule of formattingRules)if(rule.key===key)colour=ruleColour(row,rule,formattingRows)||colour;return colour?`background-color:${colour};`:''};
const tableBeforeFormatting=renderTable;
renderTable=function(){formattingRows=filtered();tableBeforeFormatting()};
function formattingSelect(label,key,values,value){return `<label class="field">${label}<select data-format-field="${key}" aria-label="${label}">${values.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(columns.find(c=>c[0]===v)?.[1]||v)}</option>`).join('')}</select></label>`}
function formattingNumber(label,key,value,disabled=false){return `<label class="field">${label}<input type="number" step="any" data-format-field="${key}" aria-label="${label}" value="${esc(value??'')}" ${disabled?'disabled':''}></label>`}
function formattingPanel(){drawer('Conditional formatting',`${btn('Create rule','fmt-new','plus')}<div class="formatting-list">${formattingRules.filter(r=>r.level===state.level).map(r=>`<article class="card"><label><input type="checkbox" data-format-enabled="${esc(r.id)}" ${r.enabled!==false?'checked':''}> ${esc(columns.find(c=>c[0]===r.key)?.[1]||r.key)}</label><p>${esc(r.mode==='Single colour'?r.operator+' '+r.value:r.palette)}</p>${btn('Edit','fmt-edit:'+r.id)}${btn('Remove','fmt-remove:'+r.id)}</article>`).join('')}</div><details open class="formatting-discover"><summary>Discover more</summary><p>Explore these rules to quickly spot performance trends in your data. You can customise these to fit your needs.</p>${['Greater than','Less than'].map(n=>`<div>${n}${btn('Try','fmt-try:'+n)}</div>`).join('')}</details>`);$('#drawer').classList.add('formatting-panel')}
function newFormattingRule(operator='Greater than'){formattingDraft={id:crypto.randomUUID(),level:state.level,mode:'Single colour',key:'Cost per results',event:'All events',operator,value:'',upper:'',colour:'Green',palette:'Green, white',minType:'Min. value',min:0,midType:'Percentage',mid:50,maxType:'Max. value',max:0,flip:false,enabled:true};formattingEditor()}
function formattingEditor(){const r=formattingDraft;drawer('Create rule',`${btn('‹ Back','formatting','','text-link')}<div class="formatting-tabs" role="tablist">${['Single colour','Colour scale'].map(m=>`<button role="tab" aria-selected="${r.mode===m}" data-action="fmt-mode:${m}">${m}</button>`).join('')}</div>${formattingSelect('If column','key',columns.filter(c=>!['delivery','actions'].includes(c[0])&&!/ ID$/.test(c[0])&&data[state.level].some(row=>finiteMetric(row[c[0]])!==null)).map(c=>c[0]).concat(data[state.level].some(row=>finiteMetric(row['Cost per results'])!==null)?[]:['Cost per results']),r.key)}${formattingSelect('For event','event',['All events',...new Set(data[state.level].map(resultType))],r.event)}${r.mode==='Single colour'?`${formattingSelect('Is','operator',formattingOperators,r.operator)}${formattingNumber(r.operator.includes('range')?'Minimum value':'Label','value',r.value)}${r.operator.includes('range')?formattingNumber('Maximum value','upper',r.upper):''}${formattingSelect('Apply colour','colour',['Red','Yellow','Green','Blue'],r.colour)}`:`${formattingSelect('Apply colours','palette',formattingPalettes,r.palette)}<div class="formatting-scale" style="background:linear-gradient(to right,${(r.flip?r.palette.split(', ').reverse():r.palette.split(', ')).map(c=>formattingColours[c]).join(',')})"></div>${btn('Flip','fmt-flip')}<div class="formatting-boundaries">${[['Minimum','min','Min. value'],['Midpoint','mid',null],['Maximum','max','Max. value']].filter(([,key])=>key!=='mid'||r.palette.split(', ').length===3).map(([label,key,auto])=>`<div>${formattingSelect(label,key+'Type',[...(auto?[auto]:[]),'Numeric','Percentage'],r[key+'Type'])}${formattingNumber(label+' value',key,r[key],/value/.test(r[key+'Type']))}</div>`).join('')}</div>`}<p id="formatting-error" role="status"></p>`,btn('Cancel','formatting')+btn('Save','fmt-save','','primary'));$('#drawer').classList.add('formatting-panel')}
const drawerBeforeFormatting=drawer;
drawer=function(...args){$('#drawer').classList.remove('formatting-panel');return drawerBeforeFormatting(...args)};
const actionBeforeFormatting=action;
action=function(value,el){if(value==='formatting'){formattingDraft=null;formattingPanel();return}if(value==='fmt-new'){newFormattingRule();return}if(value.startsWith('fmt-try:')){newFormattingRule(value.slice(8));return}if(value.startsWith('fmt-mode:')){formattingDraft.mode=value.slice(9);formattingEditor();return}if(value==='fmt-flip'){formattingDraft.flip=!formattingDraft.flip;formattingEditor();return}if(value.startsWith('fmt-edit:')){const r=formattingRules.find(r=>r.id===value.slice(9));if(r){formattingDraft=structuredClone(r);formattingEditor()}return}if(value.startsWith('fmt-remove:')){formattingRules=formattingRules.filter(r=>r.id!==value.slice(11));saveFormattingRules();formattingPanel();return}if(value==='fmt-save'){if(!validFormattingRule(formattingDraft)){$('#formatting-error').textContent='Enter valid numeric values and an ordered range.';return}formattingRules=formattingRules.filter(r=>r.id!==formattingDraft.id);formattingRules.push({...formattingDraft});saveFormattingRules();formattingPanel();return}return actionBeforeFormatting(value,el)};
document.addEventListener('input',e=>{const key=e.target.dataset.formatField;if(key&&formattingDraft)formattingDraft[key]=e.target.value});
document.addEventListener('change',e=>{const key=e.target.dataset.formatField;if(key&&formattingDraft){formattingDraft[key]=e.target.value;if(e.target.tagName==='SELECT')formattingEditor()}const id=e.target.dataset.formatEnabled;if(id){const rule=formattingRules.find(r=>r.id===id);if(rule){rule.enabled=e.target.checked;saveFormattingRules()}}});
renderTable();

function restoreFormattingRules(rules){formattingRules=Array.isArray(rules)?rules.filter(validFormattingRule).map(r=>({...r,id:r.id||crypto.randomUUID()})):[];saveFormattingRules()}
