/* Reference-backed option panels. These controls only change local state. */
const dateOptions=['Today','Yesterday','Today and yesterday','Last 7 days','Last 14 days','Last 28 days','Last 30 days','This week','Last week','This month','Last month','Maximum','Custom'];
let dateDraft={start:'',end:'',preset:'Last month',compare:false,month:7,year:2026,stage:0};
const isoLocal=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function rangeForPreset(name,now=new Date()){
 let end=new Date(now.getFullYear(),now.getMonth(),now.getDate()),start=new Date(end);
 if(name==='Yesterday'){start.setDate(start.getDate()-1);end=new Date(start)}
 else if(name==='Today and yesterday')start.setDate(start.getDate()-1);
 else if(/^Last \d+ days$/.test(name))start.setDate(start.getDate()-Number(name.match(/\d+/)[0])+1);
 else if(name==='This week')start.setDate(start.getDate()-((start.getDay()+6)%7));
 else if(name==='Last week'){start.setDate(start.getDate()-((start.getDay()+6)%7)-7);end=new Date(start);end.setDate(end.getDate()+6)}
 else if(name==='This month')start.setDate(1);
 else if(name==='Last month'){start=new Date(end.getFullYear(),end.getMonth()-1,1);end=new Date(end.getFullYear(),end.getMonth(),0)}
 else if(name==='Maximum')start=new Date(2023,0,1);
 return {start:isoLocal(start),end:isoLocal(end)};
}
showDate=function(){dateDraft={start:state.start,end:state.end,preset:state.dateLabel||'Custom',compare:!!state.compare,month:Number(state.start.slice(5,7))-1,year:Number(state.start.slice(0,4)),stage:0};drawDatePopover()};
function dateMonth(year,month){const first=new Date(year,month,1),y=first.getFullYear(),m=first.getMonth(),days=new Date(y,m+1,0).getDate();return `<section class="date-month"><header><select data-date-month="${month}" aria-label="Calendar month">${Array.from({length:12},(_,i)=>`<option value="${i}" ${i===m?'selected':''}>${new Date(2026,i,1).toLocaleDateString('en-GB',{month:'short'})}</option>`).join('')}</select><select data-date-year="${month}" aria-label="Calendar year">${Array.from({length:Math.max(9,y-new Date().getFullYear()+6)},(_,i)=>Math.min(y-4,new Date().getFullYear()-4)+i).map(n=>`<option ${n===y?'selected':''}>${n}</option>`).join('')}</select></header><div class="date-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(s=>`<span>${s}</span>`).join('')}${'<i></i>'.repeat(first.getDay())}${Array.from({length:days},(_,i)=>{const d=isoLocal(new Date(y,m,i+1));return `<button data-action="date-day:${d}" aria-label="${new Date(y,m,i+1).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}" class="${d>=dateDraft.start&&d<=dateDraft.end?'range ':''}${d===dateDraft.start||d===dateDraft.end?'edge':''}" ${d>isoLocal(new Date())?'disabled':''}>${i+1}</button>`}).join('')}</div></section>`}
function drawDatePopover(){const radio=n=>`<button class="date-preset-row" data-action="date-choice:${n}" role="radio" aria-checked="${dateDraft.preset===n}"><span class="radio-dot"></span>${n}</button>`;menu($('#date-button'),`<div class="date-menu-shell"><aside><b>Recently used</b>${['Today','Yesterday','Last month'].map(radio).join('')}<hr>${dateOptions.map(radio).join('')}</aside><section class="date-main"><div class="date-calendars">${btn('‹','date-previous','','date-nav date-prev','aria-label="Previous month"')}${dateMonth(dateDraft.year,dateDraft.month)}${dateMonth(dateDraft.year,dateDraft.month+1)}${btn('›','date-next','','date-nav date-next','aria-label="Next month"')}</div><label class="date-compare"><input type="checkbox" id="date-compare-toggle" ${dateDraft.compare?'checked':''}>Compare</label><div class="date-range-line"><span class="range-dot"></span><select id="date-preset-select" aria-label="Select preset">${dateOptions.map(n=>`<option ${n===dateDraft.preset?'selected':''}>${n}</option>`).join('')}</select><input type="date" id="date-start-input" aria-label="Start date" value="${dateDraft.start}"><span>-</span><input type="date" id="date-end-input" aria-label="End date" value="${dateDraft.end}"></div>${dateDraft.compare?`<div class="date-range-line compare-line"><span class="range-dot"></span><select aria-label="Comparison preset"><option>Previous period</option><option>Previous year</option></select><small>Comparison report must be imported.</small></div>`:''}<footer><small>Dates are shown in Pacific Time</small><span class="spacer"></span>${btn('Cancel','close-popover')}${btn('Update','date-update','','primary')}</footer></section></div>`,720);$('#popover').classList.add('date-popover');}
const menuBeforeOptions=menu;
menu=function(anchor,html,width){$('#popover').classList.remove('date-popover');menuBeforeOptions(anchor,html,width)};
const actionBeforeOptions=action;
action=function(a,el){const [key,...rest]=a.split(':'),arg=rest.join(':');switch(key){
 case 'date-choice':if(arg!=='Custom'){Object.assign(dateDraft,rangeForPreset(arg));dateDraft.month=Number(dateDraft.start.slice(5,7))-1;dateDraft.year=Number(dateDraft.start.slice(0,4))}dateDraft.preset=arg;drawDatePopover();return;
 case 'date-day':if(dateDraft.stage===0){dateDraft.start=arg;dateDraft.end=arg;dateDraft.stage=1}else{dateDraft.end=arg;if(dateDraft.end<dateDraft.start)[dateDraft.start,dateDraft.end]=[dateDraft.end,dateDraft.start];dateDraft.stage=0}dateDraft.preset='Custom';drawDatePopover();return;
 case 'date-previous':dateDraft.month--;if(dateDraft.month<0){dateDraft.month=11;dateDraft.year--}drawDatePopover();return;
 case 'date-next':dateDraft.month++;if(dateDraft.month>11){dateDraft.month=0;dateDraft.year++}drawDatePopover();return;
 case 'date-update':{const start=$('#date-start-input').value,end=$('#date-end-input').value;if(!start||!end||start>end)return toast('Choose a valid date range.');state.start=start;state.end=end;state.dateLabel=dateDraft.preset;state.compare=dateDraft.compare;state.page=0;$('#popover').hidden=true;render();return}
 case 'column-menu':{const c=columns.find(c=>c[0]===arg);menu(el,item('Sort lowest to highest',`sort-ascending:${arg}`)+item('Sort highest to lowest',`sort-descending:${arg}`)+item('Customise sorting','custom-sorting')+(arg==='name'?'':item('Remove column',`hide-column:${arg}`))+item('Reset column width','reset-widths')+item('Customise columns','custom-columns'));return}
 case 'sort-ascending':case 'sort-descending':state.sort={key:arg,dir:key==='sort-ascending'?1:-1};renderTable();return;
 case 'hide-column':state.visible=state.visible.filter(k=>k!==arg);persist();renderTable();return;
 default:return actionBeforeOptions(a,el);
}}
document.addEventListener('change',e=>{if(e.target.id==='date-preset-select')action('date-choice:'+e.target.value);if(e.target.id==='date-compare-toggle'){dateDraft.compare=e.target.checked;drawDatePopover()}if(e.target.id==='date-start-input'||e.target.id==='date-end-input'){dateDraft.start=$('#date-start-input').value;dateDraft.end=$('#date-end-input').value;dateDraft.preset='Custom'}if(e.target.hasAttribute('data-date-month')){const second=+e.target.dataset.dateMonth!==dateDraft.month;dateDraft.month=+e.target.value-(second?1:0);drawDatePopover()}if(e.target.hasAttribute('data-date-year')){dateDraft.year=+e.target.value;drawDatePopover()}});
