'use strict';
const builtinColumnPresets=Object.fromEntries(Object.entries(presets).map(([name,keys])=>[name,[...keys]]));
let savedColumnPresets=Object.create(null);
function validPresetName(name){return typeof name==='string'&&name.trim().length>0&&name.trim().length<=80&&!['__proto__','constructor','prototype'].includes(name.trim())}
function restoreColumnPresets(value){for(const name of Object.keys(savedColumnPresets))if(builtinColumnPresets[name])presets[name]=[...builtinColumnPresets[name]];else delete presets[name];savedColumnPresets=Object.create(null);if(value&&typeof value==='object'&&!Array.isArray(value))for(const [name,keys] of Object.entries(value)){if(!validPresetName(name)||!Array.isArray(keys))continue;const filtered=[...new Set(keys.filter(k=>typeof k==='string'&&columns.some(c=>c[0]===k)))];if(filtered.length){savedColumnPresets[name.trim()]=filtered;presets[name.trim()]=[...filtered]}}}
try{restoreColumnPresets(JSON.parse(localStorage.getItem(STORAGE+':column-presets')||JSON.stringify(company.columnPresets||{})))}catch{}
function persistColumnPresets(){try{localStorage.setItem(STORAGE+':column-presets',JSON.stringify(savedColumnPresets))}catch{toast('Could not save column presets in this browser.')}}
function saveNamedColumnPreset(name,keys){name=name.trim();if(!validPresetName(name)||!keys.length||keys.some(k=>!columns.some(c=>c[0]===k)))return false;const unique=[...new Set(keys)];savedColumnPresets[name]=unique;presets[name]=[...unique];state.preset=name;state.visible=[...unique];persistColumnPresets();persist();return true}
function removeNamedColumnPreset(name){if(!Object.hasOwn(savedColumnPresets,name))return;delete savedColumnPresets[name];if(builtinColumnPresets[name])presets[name]=[...builtinColumnPresets[name]];else delete presets[name];if(state.preset===name){state.preset=builtinColumnPresets[name]?name:company.presetName;state.visible=[...(presets[state.preset]||builtinColumnPresets[company.presetName])]}persistColumnPresets();persist();render()}
function selectColumnPreset(name){if(!Object.hasOwn(presets,name)||!Array.isArray(presets[name]))return false;state.preset=name;state.visible=[...presets[name]];persist();render();return true}
function presetMenuItem(name){return item(`${state.preset===name?'◉':'○'}　${esc(name)}`,'cp-select:'+encodeURIComponent(name))}
showColumns=function(anchor){const recent=[...new Set([state.preset,...Object.keys(savedColumnPresets).reverse(),company.presetName,'Performance'])].filter(n=>Object.hasOwn(presets,n));menu(anchor,heading('Recently used')+recent.slice(0,8).map(presetMenuItem).join('')+heading('Popular')+['Performance and clicks','Engagement','Delivery'].map(presetMenuItem).join('')+'<hr class="menu-separator">'+item('Discover more column presets','discover-presets')+item('View your column presets','cp-manage')+item('Compare attribution settings','attribution')+item('Conditional formatting','formatting')+item('Reset column width','reset-widths')+item('Customise columns','custom-columns','plus'),320)};
function manageColumnPresets(){modal('Your column presets',`<div class="saved-presets-list">${Object.keys(presets).map(name=>`<article><div><strong>${esc(name)}</strong><small>${presets[name].length+1} columns · ${Object.hasOwn(savedColumnPresets,name)?'Saved in this browser':'Included preset'}</small></div>${btn('Use','cp-select:'+encodeURIComponent(name))}${btn('Edit','cp-edit:'+encodeURIComponent(name))}${Object.hasOwn(savedColumnPresets,name)?btn(builtinColumnPresets[name]?'Reset':'Remove','cp-remove:'+encodeURIComponent(name)):''}</article>`).join('')}</div>`,btn('Create preset','cp-create','plus'),760)}
const actionBeforeSavedPresets=action;
action=function(value,el){if(value==='discover-presets'){menu(el,heading('Column presets')+Object.keys(presets).map(presetMenuItem).join(''));return}if(value==='ce-save'){if(!saveNamedColumnPreset(columnPresetName,columnDraft)){toast('Enter a preset name (1–80 characters) and select valid columns.');return}$('#modal').close();render();return}if(value==='cp-manage'){manageColumnPresets();return}if(value==='cp-create'){$('#modal').close();customiseColumns();columnPresetName='New preset';$('#column-preset-title').textContent=columnPresetName;return}if(value.startsWith('cp-')){const split=value.indexOf(':');let name;try{name=decodeURIComponent(value.slice(split+1))}catch{return}if(value.startsWith('cp-select:')){if(selectColumnPreset(name))$('#modal').close();return}if(value.startsWith('cp-edit:')){if(selectColumnPreset(name)){$('#modal').close();customiseColumns()}return}if(value.startsWith('cp-remove:')){removeNamedColumnPreset(name);manageColumnPresets();return}}return actionBeforeSavedPresets(value,el)};

if(!Object.hasOwn(presets,state.preset)&&validPresetName(state.preset)&&Array.isArray(state.visible))saveNamedColumnPreset(state.preset,state.visible);
