'use strict';
let sortingDraft=[],sortingShowColumns=true;
function sortFields(){return [['name',singular[state.level]],['on','Off/On'],...columns.filter(c=>c[0]!=='actions').map(c=>[c[0],c[1]])]}
function compareSortValues(a,b,key,dir){const x=a[key],y=b[key],missing=v=>v===undefined||v===null||String(v).trim()===''||v==='-'||v==='—';if(missing(x)||missing(y))return missing(x)?missing(y)?0:1:-1;if(key==='on')return (Number(!!x)-Number(!!y))*dir;if(key==='delivery'){const order=company.deliveryOrder||['Active','In draft','Campaign off','Off'];const rank=v=>{const i=order.indexOf(v);return i<0?0:order.length-i};return (rank(x)-rank(y))*dir}if(/ ID$/.test(key)&&/^\d+$/.test(x)&&/^\d+$/.test(y)){const xx=String(x).replace(/^0+(?=\d)/,''),yy=String(y).replace(/^0+(?=\d)/,'');return (xx.length-yy.length||xx.localeCompare(yy))*dir}return ((!isNaN(Number(x))&&!isNaN(Number(y)))?Number(x)-Number(y):String(x).localeCompare(String(y)))*dir}
function sortRowsByRules(rows,sort){const rules=[sort,...(sort.then||[])].filter(r=>r&&sortFields().some(([k])=>k===r.key)&&[1,-1].includes(r.dir));return rows.sort((a,b)=>{for(const r of rules){const difference=compareSortValues(a,b,r.key,r.dir);if(difference)return difference}return 0})}
function customSorting(){sortingDraft=state.sort?[{key:state.sort.key,dir:state.sort.dir},...(state.sort.then||[]).map(r=>({...r}))]:[{key:'delivery',dir:-1},{key:'on',dir:-1}];sortingShowColumns=state.sort?.showColumns!==false;drawSorting()}
function drawSorting(){modal('Customise sorting',`<div class="sorting-rules">${sortingDraft.map((r,i)=>`<div class="sorting-rule"><strong>${i?'Then by':'Sort by'}</strong><select data-sort-field="${i}" aria-label="${i?'Then by '+i:'Sort by'}">${sortFields().map(([k,label])=>`<option value="${esc(k)}" ${k===r.key?'selected':''} ${sortingDraft.some((other,j)=>j!==i&&other.key===k)?'disabled':''}>${esc(label)}</option>`).join('')}</select>${btn(r.dir===-1?'↓':'↑','sorting-flip:'+i,'','','title="'+(r.dir===-1?'Sort highest to lowest':'Sort lowest to highest')+'" aria-label="Change sort direction '+(i+1)+'"')}${i?btn('×','sorting-remove:'+i,'','','aria-label="Remove sorting option '+(i+1)+'"'):''}</div>`).join('')}</div>${btn('Add sorting option','sorting-add','plus','','id="add-sorting"')}<label class="sorting-columns"><input id="sorting-show-columns" type="checkbox" ${sortingShowColumns?'checked':''}>Show columns in this order</label><p id="sorting-error" role="status"></p>`,btn('Save','sorting-save','','primary'),600)}
function applySorting(rules,showColumns){if(!rules.length||new Set(rules.map(r=>r.key)).size!==rules.length||rules.some(r=>!sortFields().some(([key])=>key===r.key)||![1,-1].includes(r.dir)))return false;state.sort={...rules[0],then:rules.slice(1).map(r=>({...r})),showColumns};if(showColumns){const keys=rules.map(r=>r.key).filter(k=>!['name','on'].includes(k));state.visible=[...keys,...state.visible.filter(k=>!keys.includes(k))]}state.page=0;persist();render();return true}
const actionBeforeSorting=action;
action=function(value,el){if(value==='custom-sorting'){customSorting();return}if(value==='sorting-add'){const field=sortFields().find(([key])=>!sortingDraft.some(r=>r.key===key));if(field){sortingDraft.push({key:field[0],dir:-1});drawSorting()}return}if(value.startsWith('sorting-flip:')){const r=sortingDraft[Number(value.slice(13))];if(r){r.dir=-r.dir;drawSorting()}return}if(value.startsWith('sorting-remove:')){sortingDraft.splice(Number(value.slice(15)),1);drawSorting();return}if(value==='sorting-save'){if(applySorting(sortingDraft,sortingShowColumns))$('#modal').close();else $('#sorting-error').textContent='Choose a different valid field for each sorting option.';return}return actionBeforeSorting(value,el)};
document.addEventListener('change',e=>{if(e.target.dataset.sortField!==undefined){sortingDraft[Number(e.target.dataset.sortField)].key=e.target.value;drawSorting()}if(e.target.id==='sorting-show-columns')sortingShowColumns=e.target.checked});
